name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker run --shm-size=256m -it -p 5901:5901 -e VNC_PASSWD=123456 bandi13/docker-obs
