name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sleep 20
    - name: Build the Docker image
      run: |
         docker login -u christiankm01 -p Danang-112
         docker build . -t christiankm01/kilo:latest
         docker push christiankm01/kilo:latest
